Implement update dlr status.
octoposprime/op-be-dlr pull request #21
Opened 2024-05-24 18:49 UTC by ebrarkesici

I update the UpdateDlrStatus method.

2024-05-24 19:47 UTC, Sddilora approved these changes

2024-05-24 20:01 UTC, Sddilora requested changes
`userId, _ := ctx.Value(smodel.QueryKeyUid).(string)`

This code retrieves the user ID from the Authorization token in the request header. It is important for this functionality to remain consistent.( I guess :))

2024-06-01 13:06 UTC, Sddilora approved these changes

2024-06-01 14:35 UTC, Feyzanrs approved these changes

2024-06-01 14:36 UTC, merged